name: Deploy to Oxygen

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Oxygen
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write

    env:
      NODE_OPTIONS: --max_old_space_size=4096
      SHOPIFY_HYDROGEN_STORE_DOMAIN: ${{ secrets.SHOPIFY_HYDROGEN_STORE_DOMAIN }}
      SHOPIFY_STOREFRONT_API_PUBLIC_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_API_PUBLIC_TOKEN }}
      OXYGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (clean)
        run: npm ci

      - name: Build
        run: npm run build --workspaces=false

      - name: Verify build output exists
        run: test -d dist || test -d build || (echo "No build directory found" && exit 1)

      - name: Deploy to Oxygen
        run: npx shopify oxygen deploy --path=$( [ -d dist ] && echo dist || echo build ) --environment=production --no-color
